iter_num: &iter_num 20
device: &device cuda:0
reloc_coef: 0.5

data_path: ./data/test_50_10/

methods:
  # Gurobi:
  #   run_fn: run_gurobi_reloc
  #   OutputFlag: 0
  #   MIPGap: 0

  # Greedy-swap:
  #   run_fn: run_greedy_swap_reloc
  #   iter_num: *iter_num

  # Random-swap:
  #   run_fn: run_random_swap_reloc
  #   iter_num: *iter_num

  # BestResponse:
  #   iter_num: *iter_num
  #   run_fn: run_br

  # FR2FP:
  #   run_fn: run_FR2FP

  PPO-swap:
    run_fn: run_ppo_swap_reloc
    iter_num: *iter_num
    ckpt: ./logs/20251223-164951/checkpoints/epoch=280-step=4496.ckpt
    name: ppo_swap_test
    device: *device
